### ISSUE TITLE
Where to find libevent >= 2.1.2?

### ISSUE THREAD

**Issue by user1020** [ppelleti/https-example#1]
Patrick,  thanks for writing this examples. 

I am trying to compile the examples by 

```
git clone https://github.com/ppelleti/https-example.git
./configure
```

But got error saying:

```
checking for LIBEVENT... no
configure: error: Package requirements (libevent >= 2.1.2
                               libevent_pthreads >= 2.1.2
                               libevent_openssl >= 2.1.2) were not met:

Requested 'libevent >= 2.1.2' but version of libevent is 2.0.16-stable
Requested 'libevent_pthreads >= 2.1.2' but version of libevent_pthreads is 2.0.16-stable
Requested 'libevent_openssl >= 2.1.2' but version of libevent_openssl is 2.0.16-stable
```

The official page http://libevent.org/ shows the latest stable build is 2.0.21. 
Wonder where to find the libevent 2.1.2.   By the way, my PC is ubuntu 12.04.
Thanks.

**Comment by mignon-p** [comment]
The latest alpha of libevent is:

https://sourceforge.net/projects/levent/files/libevent/libevent-2.1/libevent-2.1.4-alpha.tar.gz/download

or for the very latest, clone the master from github:

https://github.com/libevent/libevent

The stable version of libevent does not allow evhttp to be used in 
conjunction with OpenSSL bufferevents.  Thus, https is only supported in 
the 2.1 series.

--Patrick

**Comment by user1020** [comment]
Thanks Patrick for the quick response. Tried the link you pointed out and now the https examples are working.   Thanks again!
