### ISSUE TITLE
Hi,i am new,and i want to ask you some questions,please help me

### ISSUE THREAD

**Issue by daniel1991721** [ppelleti/https-example#3]
I read your guid,and used your source code,after a few day`s debugging,now i can run it.But questions come,when i use whireshark to test,i can not capture SSL or HTTP packet,the only packets that i can capture are TCP`s.It confused me a lot.Could you please help me?

**Comment by mignon-p** [comment]
Hi, if your questions are about WireShark, you should [ask on the WireShark website](https://ask.wireshark.org/questions/).  If your questions are about libevent, you should ask on [the libevent mailing list](http://archives.seul.org/libevent/users/).

As I mentioned in the README, this is old code I wrote which I'm no longer maintaining, and I don't remember much about it.

Sorry I can't help you more.

**Comment by daniel1991721** [comment]
Thank you any way,sorry to bother you~~

At 2019-03-12 00:11:03, "Patrick Pelletier" <notifications@github.com> wrote:


Hi, if your questions are about WireShark, you should ask on the WireShark website. If your questions are about libevent, you should ask on the libevent mailing list.

As I mentioned in the README, this is old code I wrote which I'm no longer maintaining, and I don't remember much about it.

Sorry I can't help you more.
